---
- name: Deploy Apache
  hosts: apache
  tasks:
  - name: install latest or update
    yum: pkg=httpd state=latest
  - name: start service and auto start on boot
    service: name=httpd state=started enabled=yes
  - name: Create Hello World and fetch variable
    raw: echo "<h1>Hello World print from Centos{{ num_var }}</h1>" > /var/www/html/index.html
  - name: Open port 8080
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
  - name: Redirect port 8080 to 80 with Rich Rule
    firewalld:
      rich_rule: rule family=ipv4 forward-port port=8080 protocol=tcp to-port=80
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  - name: Restart firewall service
    service:
      name: firewalld
      state: restarted
