---
- name: Deploy Apache
  hosts: apache
  tasks:
  - name: install latest or update
    yum: pkg=httpd state=latest
  - name: start service and auto start on boot
    service: name=httpd state=started enabled=yes
  - name: Create Hello World and fetch variable
    raw: echo "<h1>Hello World print from Centos{{ num_var }}</h1>" > /var/www/html/index.html
  - name: listen on port 8080
    lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state=present
    notify:
      - restart httpd
  - name: Open port 8080
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
  - name: Restart firewall service
    service:
      name: firewalld
      state: restarted
  
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
